<?xml version="1.0" ?>
<robot name="cylinder" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="prefix" default=""/>
    <xacro:arg name="fixed" default="true"/>
    <xacro:arg name="height" default="0.0"/>
    <xacro:arg name="origin_x" default="0.943"/>
    <xacro:arg name="shelf_y" default="-0.952"/>
    <xacro:arg name="shelf_z" default="0.903"/>

    <xacro:arg name="articulation_mismatch_offset" default="0.0"/>
    <xacro:arg name="hinge_offset_x" default="0.004"/>
    <xacro:arg name="hinge_offset_y" default="0.027"/>

    <xacro:property name="prefix" default="$(arg prefix)"/>
    <xacro:property name="origin_x" default="$(arg origin_x)"/>
    <xacro:property name="shelf_y" default="$(arg shelf_y)"/>
    <xacro:property name="shelf_z" default="$(arg shelf_z)"/>
    <xacro:property name="height" default="$(arg height)"/>
    <xacro:property name="hinge_offset_x" default="$(arg hinge_offset_x)"/>
    <xacro:property name="hinge_offset_y" default="$(arg hinge_offset_y)"/>
    <xacro:property name="articulation_mismatch_offset" default="$(arg articulation_mismatch_offset)"/>

    <xacro:property name="door_length" default="0.295"/>
    <xacro:property name="door_height" default="0.90"/>
    <xacro:property name="door_width" default="0.016"/>
    <xacro:property name="handle_height" default="0.056"/> <!-- 0.026 -->
    <xacro:property name="handle_length" default="0.16"/>
    <xacro:property name="handle_offset" default="0.27"/>


    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${m}"/>
            <inertia ixx="${0.0833 * m * (y**2 + z**2)}"
                     ixy="0"
                     ixz="0"
                     iyy="${0.0833 * m * (x**2 + z**2)}"
                     iyz="0"
                     izz="${0.0833 * m * (x**2 + y**2)}"/>
        </inertial>
    </xacro:macro>

    <xacro:if value="$(arg fixed)">
        <link name="world"/>
        <joint name="fixed" type="fixed">
            <parent link="world"/>
            <child link="${prefix}cylinder_1"/>
            <origin xyz="${origin_x} ${shelf_y} ${shelf_z}" rpy="-0.008 -0.001 -3.085"/>
        </joint>
    </xacro:if>

    <link name="${prefix}cylinder_1">
        <xacro:box_inertia m="4" x="${door_width}" y="${door_length}" z="${shelf_z}"/>
        <visual>
            <origin rpy="0 0 0" xyz="0 -${door_length/2} ${-shelf_z/2}"/>
            <geometry>
                <box size="${door_width} ${door_length} ${shelf_z}"/>
            </geometry>
            <material name="shelf_material">
                <color rgba="0.0 1.0 1.0 1"/>
            </material>
        </visual>
        <visual>
            <origin xyz="0 0 ${-shelf_z}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.35" length="0.01"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 0.3"/>
            </material>
        </visual>
 
        <collision>
            <origin rpy="0 0 0" xyz="0 -${door_length/2} ${-shelf_z/2}"/>
            <geometry>
                <box size="${door_width} ${door_length} ${shelf_z}"/>
            </geometry>
        </collision>
    </link>

    <link name="${prefix}door">
        <xacro:box_inertia m="5.8" x="${door_width}" y="${door_length}" z="${door_height}"/>
        <visual>
            <origin rpy="0 0 0" xyz="0 ${door_length/2} 0"/>
            <geometry>
                <box size="${door_width} ${door_length} ${door_height}"/>
            </geometry>
            <material name="door_material">
                <color rgba="1.0 1.0 1.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 ${door_length/2} 0"/>
            <geometry>
                <box size="${door_width} ${door_length} ${door_height}"/>
            </geometry>
        </collision>
    </link>

    <link name="${prefix}door_hinge"/>
    <joint name="${prefix}door_hinge_joint" type="fixed">
        <parent link="${prefix}shelf"/>
        <child link="${prefix}door_hinge"/>
        <dynamics damping="2.0" friction="0.1"/>
        <origin xyz="0 -${door_length} ${door_height/2}"/>
    </joint>

    <link name="${prefix}axis_link"/>
    <joint name="${prefix}axis_joint" type="fixed">
        <parent link="${prefix}door_hinge"/>
        <child link="${prefix}axis_link"/>
        <origin xyz="${hinge_offset_x} ${hinge_offset_y + articulation_mismatch_offset} -0.150"/>
    </joint>

    <joint name="articulation_joint" type="revolute">
        <parent link="${prefix}axis_link"/>
        <child link="${prefix}measured_joint_link"/>
        <dynamics damping="2.0" friction="4.0"/>
        <origin xyz="0 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="100" lower="0" upper="1.57" velocity="10.0"/>
    </joint>


    <joint name="${prefix}door_link" type="fixed">
        <parent link="${prefix}measured_joint_link"/>
        <child link="${prefix}door"/>
        <origin xyz="-${hinge_offset_x} -${hinge_offset_y + articulation_mismatch_offset} 0.150"/>
    </joint>
    
    <link name="${prefix}handle_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 ${handle_length+0.01}"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 ${handle_length+0.01}"/>
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
    </link>

    <link name="${prefix}handle_support_left">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
    </link>

    <link name="${prefix}handle_support_right">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
    </link>

    <joint name="${prefix}handle_joint" type="fixed">
        <parent link="${prefix}door"/>
        <child link="${prefix}handle_link"/>
        <origin xyz="${handle_height + door_width/2} ${handle_offset} -0.15"
                rpy="0 0 0"/> <!-- height handle + half the width door, 0.30 minus some offset -->
    </joint>

    <joint name="${prefix}handle_support_left_joint" type="fixed">
        <parent link="${prefix}handle_link"/>
        <child link="${prefix}handle_support_left"/>
        <origin xyz="-${handle_height/2} 0 ${handle_length/2}" rpy="0 0 0"/>
    </joint>

    <joint name="${prefix}handle_support_right_joint" type="fixed">
        <parent link="${prefix}handle_link"/>
        <child link="${prefix}handle_support_right"/>
        <origin xyz="-${handle_height/2} 0 -${handle_length/2}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}measured_joint_link"/>

    <link name="${prefix}measured_joint_link_test"/>
    <joint name="${prefix}measured_test_handle_joint" type="fixed">
        <parent link="${prefix}handle_link"/>
        <child link="${prefix}measured_joint_link_test"/>
        <origin xyz="-0.06 -0.243 0.0" rpy="0 0 0"/>
    </joint>

    
</robot>