<?xml version="1.0" ?>
<robot name="door" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:arg name="prefix" default=""/>
    <xacro:arg name="height" default="0.0"/>
    <xacro:arg name="origin_x" default="1.0"/>
    <xacro:arg name="articulation_mismatch_offset" default="0.0"/>

    <xacro:property name="prefix" default="$(arg prefix)"/>
    <xacro:property name="origin_x" default="$(arg origin_x)"/>
    <xacro:property name="articulation_mismatch_offset" default="$(arg articulation_mismatch_offset)"/>
    <xacro:property name="height" default="$(arg height)"/>

    <link name="world"/>
    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="${prefix}door_frame"/>
        <origin xyz="${origin_x} 0.3 ${height + 0.01}" rpy="0 0 3.14"/>
    </joint>

    <link name="${prefix}door_frame">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.05 0.6 0.5"/>
            </geometry>
            <material name="frame_material">
                <color rgba="0.5 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.05 0.6 0.5"/>
            </geometry>
        </collision>
    </link>

    <link name="${prefix}door_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${0.25 - articulation_mismatch_offset}"/>
            <mass value="1.0"/>
            <inertia ixx="0.048966669" ixy="0" ixz="0" iyy="0.046466667" iyz="0" izz="0.0041666669"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${0.25 - articulation_mismatch_offset}"/>
            <geometry>
                <box size="0.02 0.6 0.5"/>
            </geometry>
            <material name="door_material">
                <color rgba="0.8 0.8 0.3 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${0.25 - articulation_mismatch_offset}"/>
            <geometry>
                <box size="0.02 0.6 0.5"/>
            </geometry>
        </collision>
    </link>

    <joint name="articulation_joint" type="revolute">
        <parent link="${prefix}door_frame"/>
        <child link="${prefix}door_link"/>
        <dynamics damping="1.0" friction="4.0"/>
        <origin xyz="0.046 0.0 ${articulation_mismatch_offset}"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" lower="0" upper="1.57" velocity="10.0"/>
    </joint>

    <link name="${prefix}handle_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.10"/>
            </geometry>
            <material name="handle_matreial">
                <color rgba="0.8 0.8 0.3 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.10"/>
            </geometry>
        </collision>
    </link>

    <joint name="${prefix}handle_joint" type="fixed">
        <parent link="${prefix}door_link"/>
        <child link="${prefix}handle_link"/>
        <origin xyz="0.055 0 ${0.47 - articulation_mismatch_offset}" rpy="1.5708 0 0"/>
        <dynamics damping="1.0" friction="2.0"/>
        <axis xyz="0 1 0"/>
    </joint>
</robot>