dynamics:
  dt: 0.015
  object_handle_link: handle_link
  object_handle_joint: handle_joint
  articulation_joint: articulation_joint
  has_filter: false
  apply_filter: false
  upper_limits: [ 2.0, 2.0, 6.28, 2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973, 1, 1]
  lower_limits: [ -2.0, -2.0, -6.28, -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973, -1, -1]
  initial_state: [ 0.0, 0.0, 0.0, 0.0, -0.52, 0.0, -1.785, 0.0, 1.10, 0.69, 0.04, 0.04,    # robot position
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,             # robot velocity
                   0.0,                                                                    # object joint position
                   0.0,                                                                    # object joint velocity
                   0,                                                                      # contact flag
                   100,                                                                    # tank energy
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,             # external torques
                   0.0, 0.0, 0.0, 0.0, -0.52, 0.0, -1.785, 0.0, 1.10, 0.69]                # desired robot position
  gains:
    base_gains:
      kp: [ 5000.0, 5000.0, 5000.0 ]
      kd: [ 600.0, 600.0, 600.0 ]
      ki: [ 0.0, 0.0, 0.0 ]
      i_max: [ 0.0, 0.0, 0.0 ]
    arm_gains:
      kp: [ 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0 ]
      kd: [ 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0 ]
      ki: [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ]
      i_max: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
    gripper_gains:
      kp: [ 100.0, 100.0 ]
      kd: [ 50.0, 50.0 ]
      ki: [ 0.0, 0.0 ]
      i_max: [ 0.0, 0.0 ]

sim_dynamics:
  dt: 0.015
  object_handle_link: sim_handle_link
  object_handle_joint: sim_handle_joint
  articulation_joint: articulation_joint
  has_filter: false
  apply_filter: false
  upper_limits: [ 2.0, 2.0, 6.28, 2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973, 1, 1]
  lower_limits: [ -2.0, -2.0, -6.28, -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973, -1, -1]
  initial_state: [ 0.0, 0.0, 0.0, 0.0, -0.52, 0.0, -1.785, 0.0, 1.10, 0.69, 0.04, 0.04,    # robot position
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,             # robot velocity
                   0.0,                                                                    # object joint position
                   0.0,                                                                    # object joint velocity
                   0,                                                                      # contact flag
                   100,                                                                    # tank energy
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,             # external torques
                   0.0, 0.0, 0.0, 0.0, -0.52, 0.0, -1.785, 0.0, 1.10, 0.69]                # desired robot position
  gains:
    base_gains:
      kp: [ 5000.0, 5000.0, 5000.0 ]
      kd: [ 600.0, 600.0, 600.0 ]
      ki: [ 0.0, 0.0, 0.0 ]
      i_max: [ 0.0, 0.0, 0.0 ]
    arm_gains:
      kp: [ 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0 ]
      kd: [ 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0 ]
      ki: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
      i_max: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
    gripper_gains:
      kp: [ 100.0, 100.0 ]
      kd: [ 50.0, 50.0 ]
      ki: [ 0.0, 0.0 ]
      i_max: [ 0.0, 0.0 ]

cost:
  regularization: [0.2, 0.2, 0.2, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  linear_weight: 100.0
  linear_weight_opening: 10.0

  angular_weight: 100.0
  angular_weight_opening: 1.0

  min_dist: 0.0
  max_reach: 0.65
  reach_weight: 0 #100
  reach_weight_slope: 0 #10

  obstacle_weight: 0
  obstacle_weight_slope: 0
  obstacle_radius: 0.8

  contact_weight: 10.0

  object_weight: 10000
  object_tolerance: 0.01

  grasp_translation_offset: [ 0.0, 0.0, 0.0 ]
  grasp_orientation_offset: [ 0, -0.7071068, 0, 0.7071068 ]    # -90deg around y

  upper_joint_limits: [ 2.0, 2.0, 6.28, 2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973 ]
  lower_joint_limits: [ -2.0, -2.0, -6.28, -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973 ]

  joint_limit_cost: 1000 #1000
  joint_limit_slope: 1000000 #100

  max_power: 0.0
  power_weight: 0.0

  handle_frame: handle_link
  tracked_frame: panda_grasp
  arm_base_frame: panda_link0

  collision_link_0: panda_link1
  collision_link_1: panda_link7
  collision_threshold: -1.0 #0.35
  collision_weight: 1000
  
safety_filter:
  input_limits: 
    active: true
    u_min: [ -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0 ]
    u_max: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]

  joint_limits: 
    active: true
    soft: false
    slack_multiplier: 0.0
    q_min: [ -2.0, -2.0, -6.28, -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973 ]
    q_max: [ 2.0, 2.0, 6.28, 2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973 ]

  cartesian_limits: 
    active: true
    soft: false
    slack_multiplier: 0.0
    max_reach: 0.65
    min_distance: 0.15

  object_avoidance:
      active: false
      soft: false
      slack_multiplier: 0.0
      min_distance: 0.2
      object_frame_id: ""
    
  passivity_constraint:
    active: true
    soft: false
    slack_multiplier: 0.0
    initial_tank_energy: 10.0
    min_tank_energy: 0.01

  first_derivative_limits: false
  ud_min: [ -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5 ]
  ud_max: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]

  second_derivative_limits: false
  udd_min: [ -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5 ]
  udd_max: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]

  verbose: false


# For valve
# grasp_translation_offset: [0.0, 0.01, 0.07]
# grasp_orientation_offset: [0.7071068, 0, 0, 0.7071068]  # -90 deg x
# For microwave
# grasp_translation_offset: [0.0, 0.0, 0.0]
# grasp_orientation_offset: [0, -0.7071068, 0, 0.7071068]    # -90deg around y
# For drawer
# grasp_translation_offset: [0.0, 0.0, 0.0]
# grasp_orientation_offset: [0, -0.7071068, 0, 0.7071068]    # -90deg around y
# For door
# grasp_translation_offset: [0.0, 0.0, 0.0]
# grasp_orientation_offset: [0, -0.7071068, 0, 0.7071068]    # -90deg around y
