<?xml version="1.0" ?>
<robot name="shelf" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="fixed" default="true"/>
    <xacro:arg name="prefix" default=""/>

    <xacro:property name="prefix" default="$(arg prefix)"/>
    <xacro:property name="door_length" default="0.363"/>
    <xacro:property name="door_height" default="0.748"/>
    <xacro:property name="door_width" default="0.018"/>
    <xacro:property name="corpus_door_gap" default="0.004"/>
    <xacro:property name="corpus_length" default="0.4"/>
    <xacro:property name="corpus_height" default="0.827"/>
    <xacro:property name="corpus_width" default="0.016"/>
    <xacro:property name="handle_height" default="0.056"/>
    <xacro:property name="handle_length" default="0.16"/>
    <xacro:property name="handle_offset_y" default="0.335"/> <!-- 0.338 -->
    <xacro:property name="handle_offset_z" default="-0.024"/>

    <xacro:property name="shelf_x" default="0.268466"/>
    <xacro:property name="shelf_y" default="-0.407"/>
    <xacro:property name="shelf_z" default="0.8299"/>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <origin rpy="0 0 0" xyz="0 ${-y/2} 0"/>
            <mass value="${m}"/>
            <inertia ixx="${0.0833 * m * (y**2 + z**2)}"
                     ixy="0"
                     ixz="0"
                     iyy="${0.0833 * m * (x**2 + z**2)}"
                     iyz="0"
                     izz="${0.0833 * m * (x**2 + y**2)}"/>
        </inertial>
    </xacro:macro>

    <xacro:if value="$(arg fixed)">
        <link name="world"/>
        <joint name="fixed" type="fixed">
            <parent link="world"/>
            <child link="${prefix}shelf"/> 0
            <origin xyz="100.272902 -0.0944762   0.830376" rpy="0.000710616 0.000859919  1.51977"/>
        </joint>
    </xacro:if>

    <link name="${prefix}shelf">
        <xacro:box_inertia m="5" x="${corpus_width}" y="${corpus_length}" z="${shelf_z}"/>
        <visual>
            <origin rpy="0 0 0" xyz="0 -${corpus_length/2} ${-shelf_z/2}"/>
            <geometry>
                <box size="${corpus_width} ${corpus_length} ${shelf_z}"/>
            </geometry>
            <material name="shelf_material">
                <color rgba="0.0 1.0 1.0 1"/>
            </material>
        </visual>
    </link>

    <link name="${prefix}door">
        <xacro:box_inertia m="3.0" x="${door_width}" y="${door_length}" z="${door_height}"/>
        <visual>
            <origin rpy="0 0 0" xyz="${-door_width/2} ${door_length/2} 0"/>
            <geometry>
                <box size="${door_width} ${door_length} ${door_height}"/>
            </geometry>
            <material name="door_material">
                <color rgba="1.0 1.0 1.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 ${door_length/2} 0"/>
            <geometry>
                <box size="${door_width} ${door_length} ${door_height}"/>
            </geometry>
            <material name="">
                <contact name="rubber"/>
            </material>
        </collision>
    </link>

    <link name="${prefix}door_hinge">
        <inertial>
            <mass value="0.01"/>
            <origin rpy="0 0 0" xyz="0.0 0 0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="${prefix}door_hinge_joint" type="fixed">
        <parent link="${prefix}shelf"/>
        <child link="${prefix}door_hinge"/>
        <origin xyz="${door_width/2} -${door_length + corpus_width +corpus_door_gap} ${door_height/2}"/>
    </joint>

    <link name="${prefix}axis_link">
        <inertial>
            <mass value="0.01"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="${prefix}axis_joint" type="fixed">
        <parent link="${prefix}door_hinge"/>
        <child link="${prefix}axis_link"/>
        <origin xyz="0.0 0.0 0.0"/>
    </joint>

    <joint name="articulation_joint" type="revolute">
        <parent link="${prefix}axis_link"/>
        <child link="${prefix}measured_joint_link"/>
        <origin xyz="0 0 0"/>
        <dynamics damping="2.0" friction="4.0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="100" lower="0" upper="1.75" velocity="10.0"/>
    </joint>


    <joint name="${prefix}door_link" type="fixed">
        <parent link="${prefix}measured_joint_link"/>
        <child link="${prefix}door"/>
        <origin xyz="0.0 0.0 0.0"/>
    </joint>

    <link name="${prefix}handle_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 ${handle_length+0.01}"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 ${handle_length+0.01}"/>
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
    </link>

    <link name="${prefix}handle_support_left">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="">
                <contact name="rubber"/>
            </material>
        </collision>
    </link>

    <link name="${prefix}handle_support_right">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="">
                <contact name="rubber"/>
            </material>
        </collision>
    </link>

    <joint name="${prefix}handle_joint" type="fixed">
        <parent link="${prefix}door"/>
        <child link="${prefix}handle_link"/>
        <origin xyz="${handle_height} ${handle_offset_y} ${handle_offset_z}"
                rpy="0 0 0"/> <!-- height handle + half the width door, 0.30 minus some offset -->
    </joint>

    <joint name="${prefix}handle_support_left_joint" type="fixed">
        <parent link="${prefix}handle_link"/>
        <child link="${prefix}handle_support_left"/>
        <origin xyz="-${handle_height/2} 0 -${handle_length/2}" rpy="0 0 0"/>
    </joint>

    <joint name="${prefix}handle_support_right_joint" type="fixed">
        <parent link="${prefix}handle_link"/>
        <child link="${prefix}handle_support_right"/>
        <origin xyz="-${handle_height/2} 0 ${handle_length/2}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}measured_joint_link">
        <inertial>
            <mass value="0.01"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>
</robot>