solver:
  rollouts: 200
  lambda: 0.0001 #0.001
  h: 10.0
  step_size: 0.01
  horizon: 1.00

  cost_ratio: 0.2
  caching_factor: 0.3
  filtering: false
  substeps: 1

  gradient_step_size: 0.5
  momentum_step_size: 0.0

  filter_type: 1
  filter_order: 1
  filter_window: 5

  adaptive_sampling: false
  input_variance: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]

  discount_factor: 1.0
  verbose: false
  threads: 8
  debug_print: false

  use_tree_search: false
  pruning_threshold: 0.05

  logging: true

  filters_type: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  filters_order: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  filters_window: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

  bound_input: true
  u_min: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
  u_max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  # expert_types: {NORM, IMP}
  expert_weights: [0.0, 1.0]
  log_data: false