joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

manipulation_controller:
  type: manipulation_royalpanda/ManipulationController
  references_file: $(find mppi_manipulation_royalpanda)/config/experiments/references.yaml

  arm_id: panda
  joint_names: [ panda_joint1, panda_joint2, panda_joint3, panda_joint4, panda_joint5, panda_joint6, panda_joint7 ]
  base_joint_names: [world_x, world_y, theta]
  i_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]  # this is actually an integral gain
  d_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
  arm_I_max: 0.1

  state_topic: /observer/state
  nominal_state_topic: /x_nom
  base_twist_topic: /ridgeback_velocity_controller/cmd_vel

  sequential: false

  policy_update_rate: 0.0  # execute as fast as possible
  reference_update_rate: 10.0
  publish_ros: true
  ros_publish_rate: 10.0
  static_optimization: false

  # Cost parameters used by the controller
  cost:
    regularization: 0.0
    linear_weight: 100.0
    linear_weight_opening: 100.0

    angular_weight: 10.0
    angular_weight_opening: 1.0

    min_dist: 0.0
    max_reach: 1.0
    reach_weight: 100
    reach_weight_slope: 10

    obstacle_weight: 0
    obstacle_weight_slope: 0
    obstacle_radius: 0.8

    contact_weight: 10.0

    object_weight: 10
    object_tolerance: 0.01

    grasp_translation_offset: [ 0.0, 0.0, 0.0 ]
    grasp_orientation_offset: [ 0, -0.7071068, 0, 0.7071068 ]    # -90deg around y

    upper_joint_limits: [ 2.0, 2.0, 6.28, 2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973 ]
    lower_joint_limits: [ -2.0, -2.0, -6.28, -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973 ]

    joint_limit_cost: 1000 #1000
    joint_limit_slope: 100 #100

  controller_gains:
    base_gains:
      kp: [ 0.0, 0.0, 0.0 ]
      kd: [ 1000.0, 1000.0, 1000.0 ]
      ki: [ 0.0, 0.0, 0.0 ]
      i_max: [ 0.0, 0.0, 0.0 ]
    arm_gains:
      kp: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
      kd: [ 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0 ]
      ki: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
      i_max: [ 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0 ]
    gripper_gains:
      kp: [ 100.0, 100.0 ]
      kd: [ 50.0, 50.0 ]
      ki: [ 0.0, 0.0 ]
      i_max: [ 0.0, 0.0 ]

  object_reference_position: 1.57

  # Parameters of the dynamics internal to the controller
  dynamics:
    dt: 0.015
    has_filter: false
    apply_filter: false
    initial_state: [ 0.0, 0.0, 0.0, 0.0, -0.52, 0.0, -1.785, 0.0, 1.10, 0.69, 0.04, 0.04,    # robot position
                     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,             # robot velocity
                     0.0,                                                                    # object joint position
                     0.0,                                                                    # object joint velocity
                     0,                                                                      # contact flag
                     100,                                                                    # tank energy
                     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]             # external torques

    gains:
      base_gains:
        kp: [ 0.0, 0.0, 0.0 ]
        kd: [ 1000.0, 1000.0, 1000.0 ]
        ki: [ 0.0, 0.0, 0.0 ]
        i_max: [ 0.0, 0.0, 0.0 ]
      arm_gains:
        kp: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
        kd: [ 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0 ]
        ki: [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ]
        i_max: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
      gripper_gains:
        kp: [ 100.0, 100.0 ]
        kd: [ 50.0, 50.0 ]
        ki: [ 0.0, 0.0 ]
        i_max: [ 0.0, 0.0 ]

  # Safety filter parameters
  # It processes the output of the sampled control action and enforces constraints
  apply_filter: false
  safety_filter:
    input_limits: true
    u_min: [ -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0 ]
    u_max: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]

    joint_limits: true
    q_min: [ -2.0, -2.0, -6.28, -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973 ]
    q_max: [ 2.0, 2.0, 6.28, 2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973 ]

    cartesian_limits: true
    max_reach: 0.65
    min_distance: 0.15

    passivity_constraint:
      active: false
      initial_tank_energy: 10.0
      min_tank_energy: 0.01

    first_derivative_limits: false
    ud_min: [ -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5 ]
    ud_max: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]

    second_derivative_limits: false
    udd_min: [ -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5 ]
    udd_max: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
    # udd_min: [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
    # udd_max: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]

    verbose: false

panda_position_controller:
  type: effort_controllers/JointGroupPositionController
  joints: ["panda_joint1",
           "panda_joint2",
           "panda_joint3",
           "panda_joint4",
           "panda_joint5",
           "panda_joint6",
           "panda_joint7"]
  panda_joint1:
    pid: { p: 120, d: 5, i: 0.0, i_clamp: 10000 }
  panda_joint2:
    pid: { p: 300, d: 10, i: 0.02, i_clamp: 10000 }
  panda_joint3:
    pid: { p: 180, d: 5, i: 0.01, i_clamp: 1 }
  panda_joint4:
    pid: { p: 180, d: 7, i: 0.01, i_clamp: 10000 }
  panda_joint5:
    pid: { p: 120, d: 7, i: 0.01, i_clamp: 1 }
  panda_joint6:
    pid: { p: 70, d: 5, i: 0.01, i_clamp: 1 }
  panda_joint7:
    pid: { p: 20, d: 2, i: 0.0, i_clamp: 1 }