<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="omav_raisim_hook">

    <!-- Properties -->
    <xacro:property name="manipulator_length" value="$(arg manipulator_length)"/>   <!-- [m] -->
    <xacro:property name="manipulator_radius" value="0.0075"/>  <!-- [m] -->

    <xacro:property name="tool_length" value="0.04"/>         <!-- [m] -->
    <xacro:property name="tool_radius" value="0.0075"/>         <!-- [m] -->

    <xacro:property name="mass_ouzel" value="4.337"/>
    <xacro:property name="ixx_ouzel" value="0.078359"/>
    <xacro:property name="iyy_ouzel" value="0.081797"/>
    <xacro:property name="izz_ouzel" value="0.153355"/>
    <xacro:property name="radius_ouzel" value="0.2"/>
    <xacro:property name="height_ouzel" value="0.3"/>

    <link name="world"/>
    <link name="odom"/>
    <joint name="odom_to_world" type="fixed">
        <parent link="world"/>
        <child link="odom"/>
    </joint>

    <joint name="odom_to_omav_x" type="prismatic">
        <parent link="odom"/>
        <child link="omav_x"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <axis xyz="1 0 0"/>
        <limit effort="1000.0" velocity="5.0" lower="-100" upper="100"/>
    </joint>

    <link name="omav_x"/>

    <joint name="omav_x_to_omav_y" type="prismatic">
        <parent link="omav_x"/>
        <child link="omav_y"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000.0" velocity="5.0" lower="-100" upper="100"/>
    </joint>

    <link name="omav_y"/>

    <joint name="omav_y_to_omav_z" type="prismatic">
        <parent link="omav_y"/>
        <child link="omav_z"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" velocity="5.0" lower="-100" upper="100"/>
    </joint>

    <link name="omav_z"/>

    <joint name="omav_z_to_omav" type="spherical">
        <parent link="omav_z"/>
        <child link="omav"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="omav">
        <inertial>
            <mass value="${mass_ouzel}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="${ixx_ouzel}" ixy="0" ixz="0" iyy="${iyy_ouzel}" iyz="0" izz="${izz_ouzel}"/>
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${radius_ouzel}" length="${height_ouzel}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${radius_ouzel}" length="${height_ouzel}"/>
            </geometry>
            <material name="">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
    </link>

    <joint name="omav_to_rod" type="fixed">
        <parent link="omav"/>
        <child link="rod"/>
        <origin rpy="$(arg omav_to_rod_angle) 0 0" xyz="${manipulator_length/2} 0.0 0.0"/>
    </joint>

    <link name="rod">
        <collision>
            <origin rpy="0 1.5708 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${manipulator_radius}" length="${manipulator_length}"/>
                <!-- <box size="${manipulator_radius*2} ${manipulator_radius*2} ${manipulator_length}"/> -->
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
        <visual>
            <origin rpy="0 1.5708 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${manipulator_radius}" length="${manipulator_length}"/>
                <!-- <box size="${manipulator_radius*2} ${manipulator_radius*2} ${manipulator_length}"/> -->
            </geometry>
            <material name="">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
    </link>

    <joint name="rod_to_hook" type="fixed">
        <parent link="rod"/>
        <child link="hook"/>
        <origin rpy="0 0 0" xyz="${manipulator_length/2} 0.0 -${tool_length/2}"/>
    </joint>

    <!-- <link name="tip">
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${tool_radius}"/>
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0.0 0"/>
            <geometry>
                <sphere radius="${tool_radius}"/>
            </geometry>
            <material name="">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
    </link> -->
<!--
    <joint name="tip_to_thick" type="fixed">
        <parent link="tip"/>
        <child link="thick"/>
        <origin rpy="0 0 0" xyz="-0.04 0.0 0.0"/>
    </joint>

    <link name="thick">
        <collision>
            <origin rpy="0 1.5708 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.015" length="0.095"/>
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
        <visual>
            <origin rpy="0 1.5708 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.015" length="0.095"/>
            </geometry>
            <material name="">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
    </link>
-->
    <!-- <joint name="tip_to_hook" type="fixed">
        <parent link="tip"/>
        <child link="hook"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 -${tool_length/2}"/>
    </joint> -->

    <link name="hook">
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${tool_radius}" length="${tool_length}"/>
                <!-- <box size="${tool_radius*2} ${tool_radius*2} ${tool_length}"/> -->
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${tool_radius}" length="${tool_length}"/>
                <!-- <box size="${tool_radius*2} ${tool_radius*2} ${tool_length}"/> -->
            </geometry>
            <material name="">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
    </link>

</robot>
