<?xml version="1.0" ?>
<robot name="drawer"  xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:arg name="height" default="0.0"/>
    <xacro:property name="height" default="$(arg height)"/>

    <link name="world"/>
    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="drawer_frame"/>
        <origin xyz="1.5 0.3 ${height + 0.01}" rpy="0 0 3.14"/>
    </joint>

    <link name="drawer_frame">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.05 0.6 0.5"/>
            </geometry>
            <material name="frame_material">
                <color rgba="0.5 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.05 0.6 0.5"/>
            </geometry>
        </collision>
    </link>

    <!--link name="door_frame_step">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.081 0.6 0.10"/>
            </geometry>
            <material name="frame_material">
                <color rgba="0.5 0.0 0.0 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.081 0.6 0.10"/>
            </geometry>
        </collision>
    </link>

    <joint name="step_joint" type="fixed">
        <parent link="door_frame"/>
        <child link="door_frame_step"/>
        <origin xyz="0.0155 0 0.31" rpy="0 0 0"/>
        <dynamics damping="1.0" friction="2.0"/>
        <axis xyz="0 1 0"/>
    </joint-->

    <link name="drawer_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <mass value="1.0"/>
            <inertia ixx="0.048966669" ixy="0" ixz="0" iyy="0.046466667" iyz="0" izz="0.0041666669"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.02 0.6 0.5"/>
            </geometry>
            <material name="drawer_material">
                <color rgba="0.8 0.8 0.3 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
            <geometry>
                <box size="0.02 0.6 0.5"/>
            </geometry>
        </collision>
    </link>

    <joint name="articulation_joint" type="prismatic">
        <parent link="drawer_frame"/>
        <child link="drawer_link"/>
        <dynamics damping="2.0" friction="4.0"/>
        <origin xyz="0.046 0 0"/>
        <axis xyz="1 0 0"/>
        <limit effort="100" lower="0" upper="0.55" velocity="10.0"/>
    </joint>

    <link name="handle_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.10"/>
            </geometry>
            <material name="handle_matreial">
                <color rgba="0.8 0.8 0.3 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.010"/>
            </geometry>
            <material name="">
                <contact name="steel"/>
            </material>
        </collision>
    </link>

    <joint name="handle_joint" type="fixed">
        <parent link="drawer_link"/>
        <child link="handle_link"/>
        <origin xyz="0.055 0 0.47" rpy="1.5708 0 0"/>
        <dynamics damping="1.0" friction="2.0"/>
        <axis xyz="0 1 0"/>
    </joint>
</robot>