<?xml version="1.0" ?>
<robot name="shelf" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="fixed" default="true"/>
    <xacro:arg name="height" default="0.0"/>
    <xacro:property name="height" default="$(arg height)"/>

    <xacro:property name="door_length" default="0.295"/>
    <xacro:property name="door_height" default="0.90"/>
    <xacro:property name="door_width" default="0.016"/>
    <xacro:property name="handle_height" default="0.026"/>
    <xacro:property name="handle_length" default="0.16"/>
    <xacro:property name="handle_offset" default="0.25"/>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${m}"/>
            <inertia ixx="${0.0833 * m * (y**2 + z**2)}"
                     ixy="0"
                     ixz="0"
                     iyy="${0.0833 * m * (x**2 + z**2)}"
                     iyz="0"
                     izz="${0.0833 * m * (z**2 + y**2)}"/>
        </inertial>
    </xacro:macro>

    <xacro:if value="$(arg fixed)">
        <link name="world"/>
        <joint name="fixed" type="fixed">
            <parent link="world"/>
            <child link="shelf"/>
            <origin xyz="-0.318 -0.510 0.904" rpy="-0.007 0.002 1.5999"/>
        </joint>
    </xacro:if>


    <link name="shelf"/>
    <link name="door">
        <xacro:box_inertia m="5.8" x="${door_width}" y="${door_length}" z="${door_height}"/>
        <visual>
            <origin rpy="0 0 0" xyz="0 ${door_length/2} 0"/>
            <geometry>
                <box size="${door_width} ${door_length} ${door_height}"/>
            </geometry>
            <material name="door_material">
                <color rgba="1.0 1.0 1.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 ${door_length/2} 0"/>
            <geometry>
                <box size="${door_width} ${door_length} ${door_height}"/>
            </geometry>
        </collision>
    </link>

    <link name="door_hinge"/>
    <joint name="door_hinge_joint" type="fixed">
        <parent link="shelf"/>
        <child link="door_hinge"/>
        <dynamics damping="2.0" friction="4.0"/>
        <origin xyz="0 -${door_length} ${door_height/2}"/>
    </joint>

    <joint name="articulation_joint" type="revolute">
        <parent link="door_hinge"/>
        <child link="door"/>
        <dynamics damping="2.0" friction="4.0"/>
        <origin xyz="0 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="100" lower="0" upper="1.57" velocity="10.0"/>
    </joint>

    <link name="handle_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 ${handle_length+0.01}"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 ${handle_length+0.01}"/>
            </geometry>
        </collision>
    </link>

    <link name="handle_support_left">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
        </collision>
    </link>

    <link name="handle_support_right">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
            <material name="handle_material">
                <color rgba="0.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${handle_height} 0.01 0.01"/>
            </geometry>
        </collision>
    </link>

    <joint name="handle_joint" type="fixed">
        <parent link="door"/>
        <child link="handle_link"/>
        <origin xyz="${handle_height + door_width/2} ${handle_offset} -0.15"
                rpy="0 0 0"/> <!-- height handle + half the width door, 0.30 minus some offset -->
    </joint>

    <joint name="handle_support_left_joint" type="fixed">
        <parent link="handle_link"/>
        <child link="handle_support_left"/>
        <origin xyz="-${handle_height/2} 0 ${handle_length/2}" rpy="0 0 0"/>
    </joint>

    <joint name="handle_support_right_joint" type="fixed">
        <parent link="handle_link"/>
        <child link="handle_support_right"/>
        <origin xyz="-${handle_height/2} 0 -${handle_length/2}" rpy="0 0 0"/>
    </joint>

    <link name="measured_joint_link"/>

    <joint name="measured_joint_handle_joint" type="fixed">
        <parent link="handle_link"/>
        <child link="measured_joint_link"/>
        <origin xyz="-0.038456463645002395 -0.24676779774627114 0.0" rpy="0 0 0"/>
    </joint>

    
</robot>