<?xml version="1.0" encoding="utf-8"?>
<robot name="valve" xmlns:xacro="http://www.ros.org/wiki/xacro">  
    <xacro:arg name="resource_prefix" default=""/>
    <xacro:arg name="resource_directory" default="$(find mppi_manipulation)/data/meshes"/>

    <xacro:property name="base_position_x" default="1.0"/>
    <xacro:property name="base_position_y" default="0.0"/>
    <xacro:property name="base_length" default="0.2"/>
    <xacro:property name="base_height" default="0.5"/>
    <xacro:property name="base_width" default="0.2"/>
    <xacro:property name="valve_type" default="lee_"/>
    <!-- 
    <xacro:arg name="height" default="0.0"/>
    <xacro:property name="height" default="$(arg height)"/> -->

    <link name="world"/>

    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="valve_base"/>
        <origin xyz="${base_position_x} ${base_position_y} ${base_height/2.0}" rpy="0.0 0 0"/>
    </joint>

    <link name="valve_base">
    </link>

    <link name="handle_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="$(arg resource_prefix)$(arg resource_directory)/valve_${valve_type}visual.obj" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
	       <geometry>
                <mesh  filename="$(arg resource_prefix)$(arg resource_directory)/valve_${valve_type}collision.obj" scale="1 1 1"/>
            </geometry>
        </collision>
    </link>

    <joint name="articulation_joint" type="revolute">
        <parent link="valve_base"/>
        <child link="handle_link"/>
        <origin xyz="0 0 ${base_height/2.0+0.2}" rpy="0 0 0"/> <!-- 1.5708 0 0 -->
        <dynamics damping="0.0" friction="0.002"/>
        <axis xyz="0 1 0"/>
        <limit upper="300.14" lower="-300.14" effort="100" velocity="1.0"/>
    </joint>
</robot>
