solver:
  rollouts: 100
  lambda: 0.0001 #0.001
  h: 10.0
  step_size: 0.01
  horizon: 1.0

  cost_ratio: 0.2
  caching_factor: 0.1
  filtering: false
  substeps: 1

  filter_type: 0
  filter_order: 2
  filter_window: 10

  filters_type: [1, 1]
  filters_order: [1, 1]
  filters_window: [5, 5]

  bound_input: true
  u_min: [-1.0, -1.0]
  u_max: [1.0, 1.0]

  spline_degree: 3
  spline_dt: 0.1
  spline_step_size: 0.01

  adaptive_sampling: false
  input_variance: [0.01, 0.01]

  discount_factor: 1.0
  verbose: false
  threads: 1
  debug_print: false

  use_tree_search: false
  pruning_threshold: 0.01      # check with 9999999
  expert_weights: [ 0.5, 0.5 ]
  log_data: true

policy_update_rate: 0.0  # execute as fast as possible
reference_update_rate: 10.0
publish_ros: true
ros_publish_rate: 10.0
gaussian_policy: false

static_optimization: false
sim_dt: 0.01