# goal
bool use_policy
bool validate
float64 timeout
string dataset_path
string policy_path
geometry_msgs/PoseStamped goal_pose
sensor_msgs/JointState initial_joint_pos


---

# result
bool goal_reached
float64 goal_reached_time

---

# feedback
float64 sim_time
